/*
 * generated by Xtext 2.36.0
 */
package kieker.otel.translation;

import org.eclipse.xtext.linking.ILinkingService;
import org.eclipse.xtext.scoping.IGlobalScopeProvider;
import org.eclipse.xtext.scoping.IScopeProvider;

import kieker.otel.translation.linking.CustomLinkerMappingRule;
import kieker.otel.translation.model.ModelGlobalScopeProvider;
import kieker.otel.translation.scoping.CompositeScopes;




/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class OtktRuntimeModule extends AbstractOtktRuntimeModule {
	
	
 /*  @Override
    public Class<? extends IGlobalScopeProvider> bindIGlobalScopeProvider() {
        return ModelGlobalScopeProvider.class;
    }*/
    @Override
    public Class<? extends IScopeProvider> bindIScopeProvider() {
        return CompositeScopes.class;
    }
    @Override
    public Class<? extends ILinkingService> bindILinkingService() {
        return CustomLinkerMappingRule.class;
    }

}
