/*
 * generated by Xtext 2.36.0
 */
package kieker.otel.translation.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import kieker.otel.translation.OtktRuntimeModule;
import kieker.otel.translation.OtktStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class OtktIdeSetup extends OtktStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new OtktRuntimeModule(), new OtktIdeModule()));
	}
	
}
