/*
 * generated by Xtext 2.36.0
 */
package kieker.otel.translation.scoping;

import org.eclipse.emf.ecore.EReference;
import org.eclipse.xtext.scoping.IScope;
import org.eclipse.xtext.scoping.Scopes;

import kieker.otel.translation.otkt.KiekerReference;
import kieker.otel.translation.otkt.KiekerMonitoringType;
import kieker.otel.translation.otkt.NewRecord;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
public class OtktScopeProvider extends AbstractOtktScopeProvider {

}
