/*
 * generated by Xtext 2.36.0
 */
package kieker.otel.translation.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class OtktUiModule extends AbstractOtktUiModule {

	public OtktUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
